name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test -- --watch=false --browsers=ChromeHeadlessNoSandbox

      - name: Azure Login
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: testThree
          slot-name: production
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: ./dist/employee-management